version: '2'

services:
  nginx:
    image: nginx:1.13.9
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  client:
    image: node:11.11
    working_dir: /var/website
    command: yarn run dev
    expose:
      - 3000
    # ports:
    #   - '3000:3000'
    volumes:
      - ./client/nextjs:/var/website
      - ./src-shared:/var/website/src-shared
      # - ./locales:/var/website/static/locales
  api:
    image: node:11.11
    working_dir: /var/website
    command: npm run start
    expose:
      - 3000
    # ports:
    #   - '3001:3000'
    volumes:
      - ./server:/var/website
      - ./src-shared:/var/website/src-shared
      # - ./locales:/var/website/locales
